---

# The base directory relative to which user specific configuration files should be stored
config_dir: "{{ ansible_env.HOME }}/.config"

neovim_config_dir: "{{ config_dir }}/nvim"
nvim_config_git_url: 'https://github.com/ConnorVoisey/nvim'

