---
galaxy_info:
  author: sthysel
  description: Install & configure neovim
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
    - name: GenericUNIX
      versions:
        - all
        - any
    - name: GenericBSD
      versions:
        - all
        - any
    - name: GenericLinux
      versions:
        - all
        - any
  galaxy_tags:
    - development
    - neovim

dependencies: []
