---

- block: 
    - name: Add neovim ppa 
      apt_repository: repo="ppa:neovim-ppa/unstable" state=present
      when: ansible_os_family == "Debian"

    - name: Install neovim from ppa
      apt: name="neovim" state="present"

    - name: use nvim for editor
      community.general.alternatives: name=editor path=/usr/bin/nvim

  become: true
  become_user: root

- block:
    - name: install nvim config
      git:
        repo: "{{nvim_config_git_url}}"
        dest: "{{neovim_config_dir}}"
