---

- block:
    - name: add php repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: install prerequisites
      apt:
        name: software-properties-common
        state: latest
        update_cache: true
  when: INSTALL_PHP
  become: true
  become_user: root

- block:
    - name: install prerequisites
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - php7.3
        - php7.3-fpm
        - php7.3-cli
        - php7.3-imagick
        - php7.3-intl
        - php7.3-redis
        - php7.3-yaml
        - php7.3-zip
        - php7.3-gnupg
        - php7.3-imap
        - php7.3-mysql
        - php7.3-gd
        - php7.3-mbstring
        - php7.3-curl
        - php7.3-xml
        - php7.3-bcmath
        - php7.3-xdebug
        - php7.3-pgsql

        - php7.4
        - php7.4-fpm
        - php7.4-cli
        - php7.4-imagick
        - php7.4-intl
        - php7.4-redis
        - php7.4-yaml
        - php7.4-zip
        - php7.4-gnupg
        - php7.4-imap
        - php7.4-mysql
        - php7.4-gd
        - php7.4-mbstring
        - php7.4-curl
        - php7.4-xml
        - php7.4-bcmath
        - php7.4-xdebug
        - php7.4-pgsql

        - php8.0
        - php8.0-fpm
        - php8.0-cli
        - php8.0-imagick
        - php8.0-intl
        - php8.0-redis
        - php8.0-yaml
        - php8.0-zip
        - php8.0-gnupg
        - php8.0-imap
        - php8.0-mysql
        - php8.0-gd
        - php8.0-mbstring
        - php8.0-curl
        - php8.0-xml
        - php8.0-bcmath
        - php8.0-xdebug
        - php8.0-pgsql

        - php8.1
        - php8.1-fpm
        - php8.1-cli
        - php8.1-imagick
        - php8.1-intl
        - php8.1-redis
        - php8.1-yaml
        - php8.1-zip
        - php8.1-gnupg
        - php8.1-imap
        - php8.1-mysql
        - php8.1-gd
        - php8.1-mbstring
        - php8.1-curl
        - php8.1-xml
        - php8.1-bcmath
        - php8.1-xdebug
        - php8.1-pgsql

        - php8.2
        - php8.2-fpm
        - php8.2-cli
        - php8.2-imagick
        - php8.2-intl
        - php8.2-redis
        - php8.2-yaml
        - php8.2-zip
        - php8.2-gnupg
        - php8.2-imap
        - php8.2-mysql
        - php8.2-gd
        - php8.2-mbstring
        - php8.2-curl
        - php8.2-xml
        - php8.2-bcmath
        - php8.2-xdebug
        - php8.2-pgsql

  when: INSTALL_PHP
  become: true
  become_user: root

- block:
    - name: install composer
      get_url:
        url: https://getcomposer.org/download/latest-stable/composer.phar
        dest: /usr/bin/composer
        mode: '0755'
  when: INSTALL_PHP
  become: true
  become_user: root

  become: true
  become_user: root
