---

- block:
  - name: registery 1
    shell: type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)

  - name: registery 2
    shell: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

  - name: install
    apt:
      name: gh
      state: present

  become: true
  become_user: root
