Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.env.enable
  config.ssh.username = "vagrant"

  # Run Ansible from the Vagrant Host
  config.vm.provision "shell" do |shell|
    shell.inline = "source /vagrant/.env && export $(cat /vagrant/.env | xargs)"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
    ansible.extra_vars = {
      ansible_user: "vagrant"
    }
    # ansible.verbose = "vvv"
  end

end

